mussel: allow multiple depth hash argument like "--volumes[0][size]=50G"

diff --git a/client/mussel/functions b/client/mussel/functions
--- a/client/mussel/functions
+++ b/client/mussel/functions
@@ -10,7 +10,7 @@ CURL_OPTS_EX=
 
 function extract_args() {
   MUSSEL_ARGS=
-  local arg= key= value=
+  local arg= key= value= key_prefix=
   while [[ $# != 0 ]]; do
     arg="$1" key= value=
     case "${arg}" in
@@ -20,8 +20,17 @@ function extract_args() {
       ;;
     --*=*)
       key=${arg%%=*}; key=${key##--}; key=${key//-/_}
-      value="${value} ${arg##--*=}"
-      eval "${key}=\"${value}\""; value="\${${key}}"; value=$(eval echo ${value}); eval "${key}=\"${value## }\""
+      if echo $key | grep -qF '['; then
+        # --volumes[0][type]=xxxx --volumes[0][size]=50G
+        #  |
+        #  V
+        # volumes_curl_args="volumes[0][type]=xxxx volumes[0][size]=50G
+        key_prefix=${key%%\[*}
+        eval "${key_prefix}_args=\"\$\{${key_prefix}_args\} ${arg##--}\""
+      else
+        value="${value} ${arg##--*=}"
+        eval "${key}=\"${value}\""; value="\${${key}}"; value=$(eval echo ${value}); eval "${key}=\"${value## }\""
+      fi
       ;;
     --*)
       key=${arg##--}; key=${key//-/_}
@@ -111,6 +120,17 @@ function strfile_type() {
      # str: key=${key}
      echo "${key}=\${${key}}"
    fi
+  "
+}
+
+function add_args_param() {
+  local param_key=$1
+  [[ -n "${param_key}" ]] || { echo "[ERROR] 'param_key' is empty (${BASH_SOURCE[0]##*/}:${LINENO})" >&2; return 1; }
+
+  eval "
+   [[ -n "\${${param_key}_args}" ]] || return 0
+
+   local i; for i in \${${param_key}_args}; do echo \"--data-urlencode '\$i'\"; done
   "
 }
 
